version: '3.7'

services:
  chalkup:
    build: .
    command: echo 'ready'
    volumes:
      - .:/srv/chalkup
      - chalkup_node_modules:/srv/chalkup/node_modules

volumes:
  chat_node_modules:      