version: '3.7'

services:
  chalkup:
    build:
      context: .
      target: development
    command: node index.js
    ports:
        - '3003:3003'
    volumes:
      - .:/srv/chalkup
      - chalkup_node_modules:/srv/chalkup/node_modules

volumes:
  chat_node_modules:      