GET http://localhost:3003/api/user/5d7f5d093968cd0eff0dbca4/sessions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlcmVuIiwiaWQiOiI1ZDdmNWQwOTM5NjhjZDBlZmYwZGJjYTQiLCJpYXQiOjE1Njg3MDg3Mzh9.SXIDoIkduLxUs52-S47cFNaHsS9Ly1it5lylH_drAck
